import React from 'react';
import Head from 'next/head';

import Container from '@material-ui/core/Container';
import MyIntervals from '@/components/MyIntervals';

export default function Intervals() {
  return (
    <Container maxWidth={false}>
      <Head>
        <title>My Intervals</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MyIntervals />
    </Container>
  )
}
