import React from 'react'
import Head from 'next/head'
import Container from '@material-ui/core/Container';

export default function Home() {

  return (
    <Container maxWidth={false}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>

      </main>
    </Container>
  )
}
