import React from 'react'
import Head from 'next/head'
import Container from '@material-ui/core/Container';
// @ts-ignore
import TelegramLoginButton from 'react-telegram-login';

export default function Home() {
  const handleTelegramResponse = (response: Object) => {
    console.log(response);
  };
  return (
    <Container maxWidth={false}>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        hello
        <TelegramLoginButton dataOnauth={handleTelegramResponse} botName="FaangInfoBot" />
      </main>
    </Container>
  )
}
